environments: # Optional. List of environments that will be used to generate secret keys when you have keys that are different between environments (e.g. debug/staging/prod). Defaults to empty.
  - Debug
  - Snapshot
  - Release
  - Production
global_secrets: # Optional. List of secrets that are the same regardless of which environment is being built. Defaults to empty.
  - AppCenterSecret
  - MarvelAPIPublicKey
  - MarvelAPIPrivateKey
environment_secrets: # Optional. This will create a secret for each entry in this list, one for each env, appending a suffix corresponding to the name of the env. Defaults to empty.
  # - MyServiceAPIKey # Will lookup for MyServiceAPIKeyDebug and MyServiceAPIKeyRelease env vars (assuming no flavor was declared)
