aggressive: false
diagnose: false
disable_update_check: false
format: xcode
index_exclude: ['DependenciesDemo/Code/Helpers/Generated/*.generated.swift']
project: null
quiet: false
report_exclude: ['DependenciesDemo/Code/Application/Services/*Service.swift']
retain_objc_annotated: true
retain_public: true
retain_unused_protocol_func_params: false
save_build_log: null
schemes:
- DependenciesDemo
strict: false
targets:
- DependenciesDemo
use_build_log: null
verbose: true
workspace: DependenciesDemo.xcworkspace
