sources:
  include:
    - ../../Packages/DependenciesDemoHelpers/Sources
  exclude:
    - ../../Packages/DependenciesDemoHelpers/Sources/Generated/Sourcery
templates:
  - ../../Templates/Sourcery/AutoInit.stencil
  - ../../Templates/Sourcery/AutoHashable.stencil
  - ../../Templates/Sourcery/AutoCodable.swifttemplate
  - ../../Templates/Sourcery/AutoEquatable.stencil
  - ../../Templates/Sourcery/AutoLenses.stencil
  - ../../Templates/Sourcery/AutoDebugDescription.swifttemplate
output: ../../Packages/DependenciesDemoHelpers/Sources/Generated/Sourcery
